version: "3.8"

services:
  api:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    image: nginx-examples-api
    env_file:
      - .env.prod

  backoffice:
    build:
      context: ./apps/backoffice/
      dockerfile: Dockerfile
    image: nginx-examples-bo
    env_file:
      - .env.prod
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-examples-rp
    ports:
      - "80:80"
    depends_on:
      - backoffice
      - api

