version: "3.8"

services:
  api:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    image: nginx-examples-api
    env_file:
      - .env.prod

  backoffice:
    build:
      context: ./apps/backoffice/
      dockerfile: Dockerfile
    image: nginx-examples-bo
    env_file:
      - .env.prod
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-examples-rp
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backoffice
      - api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


